version: "3.5"

services:
  metrics_db:
    image: openbookpublishers/metrics_db
    container_name: "metrics_db"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./config/db.env

  metrics_api:
    image: openbookpublishers/metrics_api
    container_name: "metrics_api"
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=metrics_db
    env_file:
      - ./config/api.env
      - ./config/db.env
    depends_on:
      - metrics_db

volumes:
  db:
